### ISSUE TITLE
Missing and duplicated basic options

### ISSUE THREAD

**Issue by akallabeth** [wyllianbs/xfreerdp-gui#1]
Nice script you have there, here some points that I found
* There is no way to configure modern RDP options (RFX, GFX with H264 et al)
* Sound and Microphone redirection
* `Domain` is kind of unnecessary, you have the `user@domain` and `domain\\user` syntax too
* Same is true for `Port`, you can use the `<url>:<port>` syntax
* Multimonitor options

Script argument related:
* the `/plugin` syntax is deprecated, `+clipboard` is enabled by default
* `/sound` is sufficient for hard coded sound redirection, `vc:rdpsnd,sys:alsa` is deprecated
* `/tsmf`is correct syntax, `/dvc:tsmf,sys:alsa` is deprecated. The channel is not really stable, so better deactiveate it, the RDPVOR implementation to be merged will replace this one.
* hard coding `/kbd` is a really bad idea
* `/cert-ignore` is not the best default option, better is `/cert-tofu` but they all require some feedback if something changed

Security related:
Better use the `/from-stdin` option to pass the credentials from your script so that they are not part of the command line.

**Comment by wyllianbs** [comment]
Thanks, kallabeth.

The suggested changes have been incorporated into the current script.
