### ISSUE TITLE
Support wayland

### ISSUE THREAD

**Issue by vwbusguy** [wyllianbs/xfreerdp-gui#3]
On RHEL/Fedora, at least, installing freerdp gives both xfreerdp and wlfreerdp.  It should be possible to query $XDG_SESSION_TYPE and if it's "x11", use xfreerdp, and if it's "wayland", use wlfreerdp.  All of the other options should be the same.

If you'd like, I can test it out and submit a PR?

**Comment by bmullan** [comment]
@vwbusguy 
Scott - saw your old message here.
Just in case you haven't kept up

xfreerdp3 has been released and it supports both X11 and Wayland

https://github.com/FreeRDP/FreeRDP/releases/tag/3.5.1
